package gestor.de.base.de.datos;

import java.util.Vector;
import javax.swing.JTextField;

/**
 *
 * @author diego
 */
public class Main_Screen extends javax.swing.JFrame {
    
    Database_Manager dbm;
    Login_Screen LGS;
    Vector<JTextField> tableColumns;
    
    public Main_Screen(Database_Manager D, Login_Screen LG) throws Exception{
        initComponents();
        dbm = D;
        LGS = LG;
        LGS.setVisible(false);
        this.setVisible(true);
        initComponentValues();
        tableColumns = new Vector<>();
    }
    
    private void initComponentValues() throws Exception{
        dbm.populateComboBox(ShowTableDDL_ComboBox, "SHOW TABLES;");
        dbm.populateComboBox(ShowSchemaDDL_ComboBox, dbm.showSchema());
        dbm.populateComboBox(createView_comboBox, "SHOW TABLES;");
        dbm.populateComboBox(createSchema_UsernameBox, 
                "SELECT * FROM INFORMATION_SCHEMA.USERS;");
        dbm.populateComboBox(createIndex_TableBox, "SHOW TABLES;");
        dbm.populateComboBox(createIndex_ComboBox, "SELECT COLUMN_NAME  "
                    + "FROM INFORMATION_SCHEMA.COLUMNS A INNER JOIN "
                    + "INFORMATION_SCHEMA.TABLES B ON A.TABLE_NAME = B.TABLE_NAME "
                    + "WHERE A.TABLE_SCHEMA != 'INFORMATION_SCHEMA' "
                    + "AND A.TABLE_NAME = \'" + createIndex_TableBox
                            .getSelectedItem().toString() + "\';");
        dbm.populateComboBox(schemaUpdate_OldNameBox, "SHOW SCHEMAS;");
        dbm.populateComboBox(updateUser_userBox,
                "SELECT * FROM INFORMATION_SCHEMA.USERS;");
        dbm.populateComboBox(updateIndex_ComboBox, dbm.showIndexes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_TabbedPane = new javax.swing.JTabbedPane();
        Show_Tab = new javax.swing.JPanel();
        Show_ComboBox = new javax.swing.JComboBox<>();
        Show_Button = new javax.swing.JButton();
        Show_TablePane = new javax.swing.JScrollPane();
        Show_Table = new javax.swing.JTable();
        ShowModify_Button = new javax.swing.JButton();
        ShowDelete_Button = new javax.swing.JButton();
        ShowTable_Button = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        Create_Tab = new javax.swing.JPanel();
        createTab_SubTab = new javax.swing.JTabbedPane();
        createTable_Panel = new javax.swing.JPanel();
        createIndexes_Panel = new javax.swing.JPanel();
        createIndex_NameField = new javax.swing.JTextField();
        createIndex_TableBox = new javax.swing.JComboBox<>();
        createIndex_ComboBox = new javax.swing.JComboBox<>();
        createIndex_Button = new javax.swing.JButton();
        createTriggers_Panel = new javax.swing.JPanel();
        createUsers_Panel = new javax.swing.JPanel();
        createUser_inputField = new javax.swing.JTextField();
        createUser_PasswordField = new javax.swing.JPasswordField();
        createUser_Button = new javax.swing.JButton();
        createSchema_Panel = new javax.swing.JPanel();
        createSchema_InputField = new javax.swing.JTextField();
        createSchema_UsernameBox = new javax.swing.JComboBox<>();
        createSchema_Button = new javax.swing.JButton();
        createViews_Panel = new javax.swing.JPanel();
        viewName_InputField = new javax.swing.JTextField();
        createView_comboBox = new javax.swing.JComboBox<>();
        createView_Button = new javax.swing.JButton();
        DDL_Tab = new javax.swing.JPanel();
        ShowTableDDL_ComboBox = new javax.swing.JComboBox<>();
        ShowSchemaDDL_Button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DDLTable = new javax.swing.JTable();
        ShowSchemaDDL_ComboBox = new javax.swing.JComboBox<>();
        ShowTableDDL_Button = new javax.swing.JButton();
        Update_Tab = new javax.swing.JPanel();
        updateSchema_Tab = new javax.swing.JTabbedPane();
        indexUpdate_Tab = new javax.swing.JPanel();
        updateIndex_ComboBox = new javax.swing.JComboBox<>();
        updateIndex_NewNameField = new javax.swing.JTextField();
        updateIndex_Button = new javax.swing.JButton();
        triggerUpdate_Tab = new javax.swing.JPanel();
        usersUpdate_Tab = new javax.swing.JPanel();
        updateUser_userBox = new javax.swing.JComboBox<>();
        updateUser_NewNameField = new javax.swing.JTextField();
        updateUser_PasswordField = new javax.swing.JPasswordField();
        updateUser_AdminCheckbox = new javax.swing.JCheckBox();
        updateUser_Button = new javax.swing.JButton();
        schemaUpdate_Tab = new javax.swing.JPanel();
        schemaUpdate_OldNameBox = new javax.swing.JComboBox<>();
        schemaUpdate_NewNameField = new javax.swing.JTextField();
        updateSchema_Button = new javax.swing.JButton();
        viewsUpdate_Tab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 650));

        Main_TabbedPane.setForeground(new java.awt.Color(51, 51, 51));
        Main_TabbedPane.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Main_TabbedPane.setName(""); // NOI18N
        Main_TabbedPane.setOpaque(true);

        Show_Tab.setForeground(new java.awt.Color(60, 63, 65));

        Show_ComboBox.setMaximumRowCount(7);
        Show_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tables", "Indexes", "Triggers", "Users & Databases", "Views" }));

        Show_Button.setText("Show");
        Show_Button.setToolTipText("Show a table's contents");
        Show_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Show_ButtonMouseClicked(evt);
            }
        });

        Show_Table.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Show_Table.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        Show_Table.setForeground(new java.awt.Color(0, 0, 0));
        Show_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Show_Table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Show_Table.setRowHeight(30);
        Show_Table.setRowSelectionAllowed(false);
        Show_Table.setSelectionForeground(new java.awt.Color(47, 101, 202));
        Show_TablePane.setViewportView(Show_Table);

        ShowModify_Button.setText("Edit");
        ShowModify_Button.setToolTipText("Modify a field inside the table");

        ShowDelete_Button.setText("Delete Entry");
        ShowDelete_Button.setToolTipText("Delete an entry inside the table");
        ShowDelete_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowDelete_ButtonMouseClicked(evt);
            }
        });

        ShowTable_Button.setText("Show Table");
        ShowTable_Button.setToolTipText("If it is a Table, shows the selected table.");
        ShowTable_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowTable_ButtonMouseClicked(evt);
            }
        });

        updateButton.setText("UPDATE");
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Show_TabLayout = new javax.swing.GroupLayout(Show_Tab);
        Show_Tab.setLayout(Show_TabLayout);
        Show_TabLayout.setHorizontalGroup(
            Show_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Show_TabLayout.createSequentialGroup()
                .addGroup(Show_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Show_TabLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(Show_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(Show_Button)
                        .addGap(84, 84, 84)
                        .addComponent(updateButton))
                    .addGroup(Show_TabLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(Show_TablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Show_TabLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(ShowTable_Button)
                        .addGap(104, 104, 104)
                        .addComponent(ShowModify_Button)
                        .addGap(95, 95, 95)
                        .addComponent(ShowDelete_Button)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        Show_TabLayout.setVerticalGroup(
            Show_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Show_TabLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Show_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Show_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Show_Button)
                    .addComponent(updateButton))
                .addGap(18, 18, 18)
                .addComponent(Show_TablePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(Show_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowModify_Button)
                    .addComponent(ShowDelete_Button)
                    .addComponent(ShowTable_Button))
                .addGap(41, 41, 41))
        );

        Main_TabbedPane.addTab("Show", Show_Tab);

        createTab_SubTab.setForeground(new java.awt.Color(102, 102, 102));
        createTab_SubTab.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout createTable_PanelLayout = new javax.swing.GroupLayout(createTable_Panel);
        createTable_Panel.setLayout(createTable_PanelLayout);
        createTable_PanelLayout.setHorizontalGroup(
            createTable_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 992, Short.MAX_VALUE)
        );
        createTable_PanelLayout.setVerticalGroup(
            createTable_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        createTab_SubTab.addTab("Tables", createTable_Panel);

        createIndex_NameField.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        createIndex_NameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Index Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        createIndex_TableBox.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        createIndex_TableBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Table Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N
        createIndex_TableBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                createIndex_TableBoxItemStateChanged(evt);
            }
        });

        createIndex_ComboBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        createIndex_ComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Column Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        createIndex_Button.setText("Create");
        createIndex_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createIndex_ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout createIndexes_PanelLayout = new javax.swing.GroupLayout(createIndexes_Panel);
        createIndexes_Panel.setLayout(createIndexes_PanelLayout);
        createIndexes_PanelLayout.setHorizontalGroup(
            createIndexes_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createIndexes_PanelLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(createIndexes_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createIndex_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createIndex_TableBox, 0, 406, Short.MAX_VALUE)
                    .addComponent(createIndex_NameField))
                .addGap(128, 128, 128)
                .addComponent(createIndex_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        createIndexes_PanelLayout.setVerticalGroup(
            createIndexes_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createIndexes_PanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(createIndex_NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(createIndexes_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createIndex_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createIndex_TableBox, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(createIndex_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        createTab_SubTab.addTab("Indexes", createIndexes_Panel);

        javax.swing.GroupLayout createTriggers_PanelLayout = new javax.swing.GroupLayout(createTriggers_Panel);
        createTriggers_Panel.setLayout(createTriggers_PanelLayout);
        createTriggers_PanelLayout.setHorizontalGroup(
            createTriggers_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 992, Short.MAX_VALUE)
        );
        createTriggers_PanelLayout.setVerticalGroup(
            createTriggers_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        createTab_SubTab.addTab("Triggers", createTriggers_Panel);

        createUser_inputField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        createUser_PasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        createUser_Button.setText("Create");
        createUser_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createUser_ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout createUsers_PanelLayout = new javax.swing.GroupLayout(createUsers_Panel);
        createUsers_Panel.setLayout(createUsers_PanelLayout);
        createUsers_PanelLayout.setHorizontalGroup(
            createUsers_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createUsers_PanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(createUsers_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createUser_PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(createUser_inputField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createUsers_PanelLayout.createSequentialGroup()
                .addContainerGap(607, Short.MAX_VALUE)
                .addComponent(createUser_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );
        createUsers_PanelLayout.setVerticalGroup(
            createUsers_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createUsers_PanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(createUser_inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(createUser_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(createUser_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        createTab_SubTab.addTab("Users", createUsers_Panel);

        createSchema_InputField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        createSchema_InputField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Schema Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        createSchema_UsernameBox.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        createSchema_UsernameBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        createSchema_Button.setText("Create");
        createSchema_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createSchema_ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout createSchema_PanelLayout = new javax.swing.GroupLayout(createSchema_Panel);
        createSchema_Panel.setLayout(createSchema_PanelLayout);
        createSchema_PanelLayout.setHorizontalGroup(
            createSchema_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createSchema_PanelLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(createSchema_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createSchema_UsernameBox, 0, 417, Short.MAX_VALUE)
                    .addComponent(createSchema_InputField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createSchema_PanelLayout.createSequentialGroup()
                .addContainerGap(685, Short.MAX_VALUE)
                .addComponent(createSchema_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        createSchema_PanelLayout.setVerticalGroup(
            createSchema_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createSchema_PanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(createSchema_InputField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(createSchema_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(createSchema_UsernameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        createTab_SubTab.addTab("Schema", createSchema_Panel);

        viewName_InputField.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        viewName_InputField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        createView_comboBox.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        createView_comboBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Table Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        createView_Button.setText("Create");
        createView_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createView_ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout createViews_PanelLayout = new javax.swing.GroupLayout(createViews_Panel);
        createViews_Panel.setLayout(createViews_PanelLayout);
        createViews_PanelLayout.setHorizontalGroup(
            createViews_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createViews_PanelLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(createViews_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewName_InputField)
                    .addComponent(createView_comboBox, 0, 316, Short.MAX_VALUE))
                .addGap(151, 151, 151)
                .addComponent(createView_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        createViews_PanelLayout.setVerticalGroup(
            createViews_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createViews_PanelLayout.createSequentialGroup()
                .addGroup(createViews_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createViews_PanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(viewName_InputField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createViews_PanelLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(createView_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createView_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        createTab_SubTab.addTab("Views", createViews_Panel);

        javax.swing.GroupLayout Create_TabLayout = new javax.swing.GroupLayout(Create_Tab);
        Create_Tab.setLayout(Create_TabLayout);
        Create_TabLayout.setHorizontalGroup(
            Create_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createTab_SubTab)
        );
        Create_TabLayout.setVerticalGroup(
            Create_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createTab_SubTab)
        );

        Main_TabbedPane.addTab("Create", Create_Tab);

        ShowSchemaDDL_Button.setText("Show Schema");
        ShowSchemaDDL_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowSchemaDDL_ButtonMouseClicked(evt);
            }
        });

        DDLTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(DDLTable);

        ShowTableDDL_Button.setText("Show Table");
        ShowTableDDL_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowTableDDL_ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DDL_TabLayout = new javax.swing.GroupLayout(DDL_Tab);
        DDL_Tab.setLayout(DDL_TabLayout);
        DDL_TabLayout.setHorizontalGroup(
            DDL_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DDL_TabLayout.createSequentialGroup()
                .addGroup(DDL_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DDL_TabLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DDL_TabLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(DDL_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ShowSchemaDDL_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShowTableDDL_ComboBox, 0, 417, Short.MAX_VALUE))
                        .addGap(115, 115, 115)
                        .addGroup(DDL_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ShowSchemaDDL_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShowTableDDL_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        DDL_TabLayout.setVerticalGroup(
            DDL_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DDL_TabLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(DDL_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowTableDDL_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowTableDDL_Button))
                .addGap(18, 18, 18)
                .addGroup(DDL_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowSchemaDDL_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowSchemaDDL_Button))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        Main_TabbedPane.addTab("DDL", DDL_Tab);

        updateSchema_Tab.setFocusable(false);
        updateSchema_Tab.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        indexUpdate_Tab.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        updateIndex_ComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Index Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        updateIndex_NewNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Index Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        updateIndex_Button.setText("Update");
        updateIndex_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateIndex_ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout indexUpdate_TabLayout = new javax.swing.GroupLayout(indexUpdate_Tab);
        indexUpdate_Tab.setLayout(indexUpdate_TabLayout);
        indexUpdate_TabLayout.setHorizontalGroup(
            indexUpdate_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexUpdate_TabLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(indexUpdate_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateIndex_NewNameField)
                    .addComponent(updateIndex_ComboBox, 0, 400, Short.MAX_VALUE))
                .addGap(120, 120, 120)
                .addComponent(updateIndex_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        indexUpdate_TabLayout.setVerticalGroup(
            indexUpdate_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexUpdate_TabLayout.createSequentialGroup()
                .addGroup(indexUpdate_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indexUpdate_TabLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(updateIndex_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(indexUpdate_TabLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(updateIndex_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateIndex_NewNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        updateSchema_Tab.addTab("Indexes", indexUpdate_Tab);

        javax.swing.GroupLayout triggerUpdate_TabLayout = new javax.swing.GroupLayout(triggerUpdate_Tab);
        triggerUpdate_Tab.setLayout(triggerUpdate_TabLayout);
        triggerUpdate_TabLayout.setHorizontalGroup(
            triggerUpdate_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 992, Short.MAX_VALUE)
        );
        triggerUpdate_TabLayout.setVerticalGroup(
            triggerUpdate_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        updateSchema_Tab.addTab("Trigger", triggerUpdate_Tab);

        updateUser_userBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        updateUser_NewNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Username", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        updateUser_PasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Password", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        updateUser_AdminCheckbox.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        updateUser_AdminCheckbox.setText("Admin");

        updateUser_Button.setText("Update");
        updateUser_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateUser_ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout usersUpdate_TabLayout = new javax.swing.GroupLayout(usersUpdate_Tab);
        usersUpdate_Tab.setLayout(usersUpdate_TabLayout);
        usersUpdate_TabLayout.setHorizontalGroup(
            usersUpdate_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersUpdate_TabLayout.createSequentialGroup()
                .addGroup(usersUpdate_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersUpdate_TabLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(usersUpdate_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateUser_PasswordField)
                            .addComponent(updateUser_NewNameField)
                            .addComponent(updateUser_userBox, 0, 388, Short.MAX_VALUE))
                        .addGap(143, 143, 143)
                        .addComponent(updateUser_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(usersUpdate_TabLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(updateUser_AdminCheckbox)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        usersUpdate_TabLayout.setVerticalGroup(
            usersUpdate_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersUpdate_TabLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(updateUser_userBox, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(usersUpdate_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersUpdate_TabLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(updateUser_NewNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(usersUpdate_TabLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(updateUser_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(updateUser_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(updateUser_AdminCheckbox)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        updateSchema_Tab.addTab("Users", usersUpdate_Tab);

        schemaUpdate_OldNameBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Old Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        schemaUpdate_NewNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16))); // NOI18N

        updateSchema_Button.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        updateSchema_Button.setText("Update");
        updateSchema_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateSchema_ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout schemaUpdate_TabLayout = new javax.swing.GroupLayout(schemaUpdate_Tab);
        schemaUpdate_Tab.setLayout(schemaUpdate_TabLayout);
        schemaUpdate_TabLayout.setHorizontalGroup(
            schemaUpdate_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schemaUpdate_TabLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(schemaUpdate_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(schemaUpdate_NewNameField)
                    .addComponent(schemaUpdate_OldNameBox, 0, 383, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, schemaUpdate_TabLayout.createSequentialGroup()
                .addContainerGap(621, Short.MAX_VALUE)
                .addComponent(updateSchema_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        schemaUpdate_TabLayout.setVerticalGroup(
            schemaUpdate_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schemaUpdate_TabLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(schemaUpdate_OldNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateSchema_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(schemaUpdate_NewNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        updateSchema_Tab.addTab("Schema", schemaUpdate_Tab);

        javax.swing.GroupLayout viewsUpdate_TabLayout = new javax.swing.GroupLayout(viewsUpdate_Tab);
        viewsUpdate_Tab.setLayout(viewsUpdate_TabLayout);
        viewsUpdate_TabLayout.setHorizontalGroup(
            viewsUpdate_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 992, Short.MAX_VALUE)
        );
        viewsUpdate_TabLayout.setVerticalGroup(
            viewsUpdate_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        updateSchema_Tab.addTab("Views", viewsUpdate_Tab);

        javax.swing.GroupLayout Update_TabLayout = new javax.swing.GroupLayout(Update_Tab);
        Update_Tab.setLayout(Update_TabLayout);
        Update_TabLayout.setHorizontalGroup(
            Update_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateSchema_Tab)
        );
        Update_TabLayout.setVerticalGroup(
            Update_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateSchema_Tab)
        );

        Main_TabbedPane.addTab("Update", Update_Tab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_TabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_TabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowTable_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowTable_ButtonMouseClicked
        
    }//GEN-LAST:event_ShowTable_ButtonMouseClicked

    private void Show_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show_ButtonMouseClicked
        int option = Show_ComboBox.getSelectedIndex();
        
        /*
            0 - Tables
            1 - Indexes
            2 - Triggers
            3 - Users & Databases
            4 - Views
        */
        try {
            
            if (option == 0) {
                dbm.populateTable(Show_Table, dbm.showTables());
            }
            else if (option == 1) {
                dbm.populateTable(Show_Table, dbm.showIndexes());
            }
            else if (option == 2) {
                dbm.populateTable(Show_Table, dbm.showTriggers());
            }
            else if (option == 3) {
                dbm.populateTable(Show_Table, dbm.showUsers_Schema());
            }
            else if (option == 4) {
                dbm.populateTable(Show_Table, dbm.showViews());
            }
            
        } catch (Exception e) {
            System.out.println("Error in executing a show function!\n");
            e.printStackTrace();
        }
    }//GEN-LAST:event_Show_ButtonMouseClicked

    //Testing Pending
    private void ShowDelete_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowDelete_ButtonMouseClicked
        String selectedText = 
                Show_Table.getValueAt(Show_Table.getSelectedRow(), 2)
                        .toString();
        int selectedRow = 
                Show_Table.getSelectedRow();
        
        int selectedColumn = 
                Show_Table.getSelectedColumn();
        
        String username = Show_Table.getValueAt(Show_Table.getSelectedRow(), 0)
                .toString();
        
        String schemaName = Show_Table.getValueAt(Show_Table.getSelectedRow(), 5)
                .toString();
        
        System.out.println(selectedText);
        
        int selectedIndex = Show_ComboBox.getSelectedIndex();
        
        try {
            if (selectedIndex == 0) {
                dbm.executeSQL(dbm.deleteTable(selectedText));
            }
            else if (selectedIndex == 1) {
                dbm.executeSQL(dbm.deleteIndex(selectedText));
            }
            else if (selectedIndex == 2) {
                dbm.executeSQL(dbm.deleteTrigger(selectedText));
            }
            else if (selectedIndex == 3 && selectedColumn == 0) {
                dbm.executeSQL(dbm.deleteUser(selectedText));
            }
            else if (selectedIndex == 3 && selectedColumn == 5) {
                dbm.executeSQL(dbm.deleteSchema(selectedText));
            }
            else if (selectedIndex == 4) {
                dbm.executeSQL(dbm.deleteView(selectedText));
            }
        } catch (Exception e) {
            System.out.println("Error in "
                    + "executing a delete function!\n");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_ShowDelete_ButtonMouseClicked

    private void ShowSchemaDDL_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowSchemaDDL_ButtonMouseClicked
        try {
            dbm.populateTable(DDLTable,
                    dbm.showUsersAndDatabasesDDL(
                    ShowSchemaDDL_ComboBox
                            .getSelectedItem()
                            .toString()));
            
        }catch (Exception e) {
            System.out.println("Error when populating DDL table. "
                    + "~Schema variant.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_ShowSchemaDDL_ButtonMouseClicked

    private void ShowTableDDL_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowTableDDL_ButtonMouseClicked
        try {
            dbm.populateTable(DDLTable,
                    dbm.showTableDDL(
                    ShowTableDDL_ComboBox
                            .getSelectedItem()
                            .toString()));
            
        }catch (Exception e) {
            System.out.println("Error when populating DDL table. "
                    + "~Table variant.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_ShowTableDDL_ButtonMouseClicked

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        try {
            initComponentValues();
        } catch (Exception e) {
            System.out.println("Error when initializing components!");
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateButtonMouseClicked

    private void createIndex_TableBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_createIndex_TableBoxItemStateChanged
        try {
            dbm.populateComboBox(createIndex_ComboBox, "SELECT COLUMN_NAME  "
                    + "FROM INFORMATION_SCHEMA.COLUMNS A INNER JOIN "
                    + "INFORMATION_SCHEMA.TABLES B ON A.TABLE_NAME = B.TABLE_NAME "
                    + "WHERE A.TABLE_SCHEMA != 'INFORMATION_SCHEMA' "
                    + "AND A.TABLE_NAME = \'" + createIndex_TableBox
                            .getSelectedItem().toString() + "\';");
            
        }catch(Exception e) {
            System.out.println("Error when loading components into the Columns "
                    + "ComboBox.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_createIndex_TableBoxItemStateChanged

    private void createView_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createView_ButtonMouseClicked
        String viewName = viewName_InputField.getText();
        String tableName = createView_comboBox.getSelectedItem().toString();
        
        try {
            dbm.executeSQL(dbm.createView(viewName, tableName));
        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_createView_ButtonMouseClicked

    private void createSchema_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createSchema_ButtonMouseClicked
        String schemaName = createSchema_InputField.getText();
        String username = createSchema_UsernameBox.getSelectedItem().toString();
        
        try {
            dbm.executeSQL(dbm.createSchema(schemaName, username));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_createSchema_ButtonMouseClicked

    private void createIndex_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createIndex_ButtonMouseClicked
        String indexName = createIndex_NameField.getText();
        String tableName = createIndex_TableBox.getSelectedItem().toString();
        String columnName = createIndex_ComboBox.getSelectedItem().toString();
        
        try {
            dbm.executeSQL(dbm.createIndex(indexName, tableName, columnName));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_createIndex_ButtonMouseClicked

    private void updateIndex_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateIndex_ButtonMouseClicked
        String oldIndexName = updateIndex_ComboBox.getSelectedItem().toString();
        String newIndexName = updateIndex_NewNameField.getText();
        
        try {
            dbm.executeSQL(dbm.updateIndex(oldIndexName, newIndexName));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateIndex_ButtonMouseClicked

    private void updateUser_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateUser_ButtonMouseClicked
        String userName = updateUser_userBox.getSelectedItem().toString();
        String newUsername = updateUser_NewNameField.getText();
        String newPassword = updateUser_PasswordField.getPassword().toString();
        boolean getAdminRights = updateUser_AdminCheckbox.isSelected();
        
        try {
            if (!newUsername.isEmpty()) {
                dbm.executeSQL(dbm.updateUserRename(userName, newUsername));
            }
            if (newUsername.isEmpty() && (!newPassword.isEmpty())) {
                dbm.executeSQL(dbm.updateUserPassword(userName, newPassword));
            }
            else if ((!newUsername.isEmpty()) && (!newPassword.isEmpty())) {
                dbm.executeSQL(dbm.updateUserPassword(newUsername, newPassword));
            }
            if (newUsername.isEmpty()) {
                dbm.executeSQL(dbm.updateUserAdmin(userName, getAdminRights));
            }
            else if(!newUsername.isEmpty()) {
                dbm.executeSQL(dbm.updateUserAdmin(newUsername, getAdminRights));
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateUser_ButtonMouseClicked

    private void createUser_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createUser_ButtonMouseClicked
        String username = createUser_inputField.getText();
        String password = createUser_PasswordField.getPassword().toString();
        
        try {
            dbm.executeSQL(dbm.createUser(username, password));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_createUser_ButtonMouseClicked

    private void updateSchema_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateSchema_ButtonMouseClicked
        String schemaName = schemaUpdate_OldNameBox.getSelectedItem().toString();
        String newSchemaName = schemaUpdate_NewNameField.getText();
        
        try {
            dbm.executeSQL(dbm.updateSchema(schemaName, newSchemaName));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateSchema_ButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Create_Tab;
    private javax.swing.JTable DDLTable;
    private javax.swing.JPanel DDL_Tab;
    private javax.swing.JTabbedPane Main_TabbedPane;
    private javax.swing.JButton ShowDelete_Button;
    private javax.swing.JButton ShowModify_Button;
    private javax.swing.JButton ShowSchemaDDL_Button;
    private javax.swing.JComboBox<String> ShowSchemaDDL_ComboBox;
    private javax.swing.JButton ShowTableDDL_Button;
    private javax.swing.JComboBox<String> ShowTableDDL_ComboBox;
    private javax.swing.JButton ShowTable_Button;
    private javax.swing.JButton Show_Button;
    private javax.swing.JComboBox<String> Show_ComboBox;
    private javax.swing.JPanel Show_Tab;
    private javax.swing.JTable Show_Table;
    private javax.swing.JScrollPane Show_TablePane;
    private javax.swing.JPanel Update_Tab;
    private javax.swing.JButton createIndex_Button;
    private javax.swing.JComboBox<String> createIndex_ComboBox;
    private javax.swing.JTextField createIndex_NameField;
    private javax.swing.JComboBox<String> createIndex_TableBox;
    private javax.swing.JPanel createIndexes_Panel;
    private javax.swing.JButton createSchema_Button;
    private javax.swing.JTextField createSchema_InputField;
    private javax.swing.JPanel createSchema_Panel;
    private javax.swing.JComboBox<String> createSchema_UsernameBox;
    private javax.swing.JTabbedPane createTab_SubTab;
    private javax.swing.JPanel createTable_Panel;
    private javax.swing.JPanel createTriggers_Panel;
    private javax.swing.JButton createUser_Button;
    private javax.swing.JPasswordField createUser_PasswordField;
    private javax.swing.JTextField createUser_inputField;
    private javax.swing.JPanel createUsers_Panel;
    private javax.swing.JButton createView_Button;
    private javax.swing.JComboBox<String> createView_comboBox;
    private javax.swing.JPanel createViews_Panel;
    private javax.swing.JPanel indexUpdate_Tab;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField schemaUpdate_NewNameField;
    private javax.swing.JComboBox<String> schemaUpdate_OldNameBox;
    private javax.swing.JPanel schemaUpdate_Tab;
    private javax.swing.JPanel triggerUpdate_Tab;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updateIndex_Button;
    private javax.swing.JComboBox<String> updateIndex_ComboBox;
    private javax.swing.JTextField updateIndex_NewNameField;
    private javax.swing.JButton updateSchema_Button;
    private javax.swing.JTabbedPane updateSchema_Tab;
    private javax.swing.JCheckBox updateUser_AdminCheckbox;
    private javax.swing.JButton updateUser_Button;
    private javax.swing.JTextField updateUser_NewNameField;
    private javax.swing.JPasswordField updateUser_PasswordField;
    private javax.swing.JComboBox<String> updateUser_userBox;
    private javax.swing.JPanel usersUpdate_Tab;
    private javax.swing.JTextField viewName_InputField;
    private javax.swing.JPanel viewsUpdate_Tab;
    // End of variables declaration//GEN-END:variables
}
